### ISSUE TITLE
Recommend new section: Technology Considerations

### ISSUE THREAD

**Issue by joshbruce** [BrianGilmanGSA/openIAE#23]
http://briangilmangsa.github.io/openIAE/sam_web_standards/

The main page for the SAM Web Standards includes a lot of sections that describe how SAM should execute certain technological considerations (no www). This might be better served by a section called something like "technology considerations"...or a different area within openIAE as a whole.

This move would allow for the inclusion of text describing how the guide(s) and CSS usage and inheritance.

**Comment by joshbruce** [comment]
Maybe change this to "For Developers"

**Comment by jbruce-gsa** [comment]
See PR #33

**Comment by joshbruce** [comment]
See PR #35
