### ISSUE TITLE
Add CSS instructions to "Visual Style" page

### ISSUE THREAD

**Issue by joshbruce** [BrianGilmanGSA/openIAE#24]
We had a request to create some verbiage around guide and CSS inheritance. I'm not sure if these should be in the same place or separate places. Part of me says that the CSS inheritance and dependencies should go in the "Visual Style" while the Guide should go in the main page - but I'm not sure.

**Comment by joshbruce** [comment]
Duplicate of #27

**Comment by jbruce-gsa** [comment]
See PR #33

**Comment by joshbruce** [comment]
See PR #35
