### ISSUE TITLE
Select which typography pairing to use

### ISSUE THREAD

**Issue by joshbruce** [BrianGilmanGSA/openIAE#26]
https://playbook.cio.gov/designstandards/visual-style/#pairings

The US Web Standards allows for multiple pairings. Moving forward, I recommend IAE/SAM decides on one pairing to make the interpretation of the US Web Standards easier to apply with regard to font family and pairings.

**Comment by joshbruce** [comment]
Duplicate of: #22

**Comment by joshbruce** [comment]
See PR: #30

**Comment by BrianGilmanGSA** [comment]
Accepted in PR #30
