### ISSUE TITLE
Determine overall canvas color

### ISSUE THREAD

**Issue by joshbruce** [BrianGilmanGSA/openIAE#28]
https://www.teamunify.com/yusa/__doc__/graphic_standards.pdf

If you do a search for "canvas" - this basically describes the concept for this issue. By selecting one, or multiple section canvas colors, we would also go a long way toward a common look and feel.

**Comment by joshbruce** [comment]
Updated SAM Web Standard w/ a preliminary based on the landing page designs.

See PR #30 for details.

**Comment by BrianGilmanGSA** [comment]
Accepted in PR #30
