### ISSUE TITLE
secondary navigation glitch

### ISSUE THREAD

**Issue by jenbesergsa** [BrianGilmanGSA/openIAE#54]
![glitch](https://cloud.githubusercontent.com/assets/17324078/15546316/70a4f71c-226d-11e6-888c-249c626cd8be.PNG)

http://www.google.com/url?q=http%3A%2F%2Fbriangilmangsa.github.io%2Fsam-web-design-standards%2Fcomponents%2Fnavigation%2F&sa=D&sntz=1&usg=AFQjCNEnhDdBxGv9L51iELEcrJ7fS8Wfyw

**Comment by jenbesergsa** [comment]
Resolution: 1366x768

**Comment by joshbruce** [comment]
Moved to https://github.com/BrianGilmanGSA/sam-web-design-standards
